"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _power_generation_chart from './power-generation-chart.bones.json'
import _co2_intensity_chart from './co2-intensity-chart.bones.json'

registerBones({
  "power-generation-chart": _power_generation_chart,
  "co2-intensity-chart": _co2_intensity_chart,
})
